### ISSUE TITLE
Upgrading to latest jenkins?

### ISSUE THREAD

**Issue by hrj** [openshift/jenkins-cloud-plugin#27]
I am new to openshift. I successfully created an app with a jenkins cartridge (through the web ui). The jenkins version installed is 1.509.1.

How do I upgrade to the latest version : 1.532.3 ?

I tried cloning the git repo for my cartridge. But it is empty except for a README.md file.

Thanks for any help!

**Comment by robertoandrade** [comment]
Jenkins is now at 1.617 and some of my plugins are only compatible with 1.580.1 and above, the current version on OpenShift is 1.565. Is there any plans to keep OpenShift up to date with the latest compatible version of Jenkins?

**Comment by bparees** [comment]
@robertoandrade we've been heads down on v3 but yes we'll take a look at updating this post-3.0.

In the meantime, you can always run any jenkins war you want per my comment above.  Did you try that and run into issues?

**Comment by lfischer** [comment]
@bparees any news on this issue? Looks like the PR is already merged.

**Comment by bparees** [comment]
@abhgupta any plans on the horizon to update the level of jenkins in v2/online?

**Comment by abhgupta** [comment]
@bparees we can target this for the early Dec release of OpenShift Online

**Comment by XericZephyr** [comment]
@bparees @abhgupta Any updates on the newer version Jenkins with openshift?

**Comment by marktyers** [comment]
Jenkins LTS is currently at v2.3 but the version installed by OpenShift is stuck at v1.6, are there any plans to install this newer version?

**Comment by bparees** [comment]
@marktyers are you referring to the openshift v2 environment, or the new openshift v3 devpreview environment?

**Comment by marktyers** [comment]
Either would suffice.

**Comment by bparees** [comment]
@marktyers the v3 dev preview environment has a jenkins v2 image available, it should be what you get if you instantiate the jenkins template.
