### ISSUE TITLE
Upgrading Jenkins to 1.642.1?

### ISSUE THREAD

**Issue by ThunderGemios10** [openshift/jenkins-cloud-plugin#47]
Hello! I just installed Jenkins on OpenShift and i want to update jenkins. Is there any way? I can't replace .war directly since it is owned by root.

**Comment by bparees** [comment]
You'd need to docker build your own layer on top  of the image to change
the file. Which you can do via an openshift docker strategy build.  And
then use that customized image instead of the provided one.

Ben Parees | OpenShift

**Comment by bparees** [comment]
sorry I guess you were referring to v2 and not v3.

You can supply your own war file, the Jenkins cartridge supports a JENKINS_WAR_PATH env variable.  Supply your war in your gear and specify the env variable to point to it:
https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-jenkins/bin/control#L76
